module.exports = {
  name: '后台管理系统',
  prefix: 'antdAdmin',
  footerText: 'leafdream  © 2017',
  logo: '/logo.png',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'https://backend-test.10colour.com',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['https://backend-test.10colour.com'],
  openPages: ['/login'],
  apiPrefix: '',
  api: {
    loginCheck: '/login',
    adminLogin: '/session',
    adminLogout: '/logout',
    adminList: '/admin/list',
    admin: '/admin/:id',
    dashboard: '/dashboard',
    valleyList: '/sns/valley/list',
    valley: '/sns/valley/:id',
    elfList:'/elf/elf/list',
    elf: '/elf/elf/:id',
    topicList:'/sns/topic/list',
    topic: '/sns/topic/:id',
    topicCategoryList:'/sns/topicCategory/list',
    topicCategory: '/sns/topicCategory/:id',
    topicBriefList: '/sns/topicBrief/list',
    topicBrief: '/sns/topicBrief/:id',
    userList: '/user/list',
    broadcastList: '/broadcast/list',
    broadcast: '/broadcast/:id',
    broadcastCommentlist: '/broadcast/comment/list',
    broadcastComment: '/broadcast/:broadcastId/comment/:id',
    photoList: '/user/photo/list',
    photo: '/user/photo/:id',
    newsList: '/news/list',
    news: '/news/:id',
    newsCategoryList: '/newsCategory/list',
    newsCategory: '/newsCategory/:id',
    photoUpdate: '/user/photo/batchUpdate',
    videoList: '/user/video/list',
    videoUpdate: '/user/video/batchUpdate',
    newsLibList: '/newsLib/list',
    newsLib: '/newsLib/:id',
    newsLibBatchToNews: '/newsLib/batchToNews',
    uploadfile: '/upload',
    channelList: '/channel/list',
    channel: '/channel/:id',
    quizList: '/user/quiz/list',
    quiz: '/user/quiz/:id',
    tagCategoryList: '/tagCategory/list',
    tagCategory: '/tagCategory/:id',
    tagList: '/tag/list',
    tag: '/tag/:id',
  },
};
