module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: 'Dashboard',
    router: '/dashboard',
  },
  {
    id: 2,
    bpid: 1,
    name: '系统管理',
    icon: 'setting',
  },
  {
    id: 21,
    mpid: 2,
    bpid: 2,
    name: '系统管理员',
    icon: 'user',
    router: '/admin/list',
  },
  {
    id: 3,
    bpid: 1,
    name: '十色谷管理',
    icon: 'api',
  },
  {
    id: 31,
    bpid: 3,
    mpid: 3,
    name: '十色谷配置',
    icon: 'api',
    router: '/tencolourValley/tencolour',
  },
  {
    id: 32,
    bpid: 3,
    mpid: 3,
    name: '精灵配置',
    icon: 'api',
    router: '/tencolourValley/elf',
  },
  {
    id: 35,
    bpid: 3,
    mpid: 3,
    name: '话题管理',
    icon: 'api',
    router: '/tencolourValley/topic',
  },
  {
    id: 36,
    bpid: 3,
    mpid: 3,
    name: '话题分类管理',
    icon: 'api',
    router: '/tencolourValley/topicCategory',
  },
  {
    id: 37,
    bpid: 3,
    mpid: 3,
    name: '快捷标题管理',
    icon: 'api',
    router: '/tencolourValley/topicBrief',
  },
  {
    id: 38,
    bpid: 3,
    mpid: 3,
    name: '栏目管理',
    icon: 'api',
    router: '/tencolourValley/channel',
  },
  {
    id: 5,
    bpid: 1,
    name: 'APP用户管理',
    icon: 'code-o',
  },
  {
    id: 51,
    bpid: 5,
    mpid: 5,
    name: '用户列表',
    icon: 'user',
    router: '/appUserManage/userList',
  },
  {
    id: 52,
    bpid: 5,
    mpid: 5,
    name: '相册',
    icon: 'camera-o',
    router: '/user/photo',
  },
  {
    id: 53,
    bpid: 5,
    mpid: 5,
    name: '视频',
    icon: 'video-camera',
    router: '/user/video',
  },
  {
    id: 54,
    bpid: 5,
    mpid: 5,
    name: '测试题',
    icon: 'question-circle-o',
    router: '/user/quiz',
  },
  {
    id: 55,
    bpid: 5,
    mpid: 5,
    name: '标签',
    icon: 'tag-o',
    router: '/user/tag',
  },
  {
    id: 56,
    bpid: 5,
    mpid: 5,
    name: '标签类别',
    icon: 'tags-o',
    router: '/user/tagCategory',
  },
  {
    id: 6,
    bpid: 1,
    name: '资讯管理',
    icon: 'setting',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: '资讯管理',
    router: '/news/list',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: '资讯类别管理',
    router: '/newsCategory/list',
  },
  {
    id: 63,
    bpid: 6,
    mpid: 6,
    name: '资讯库管理',
    router: '/newsLib/list',
  },
  {
    id: 7,
    bpid: 1,
    name: '广播管理',
    icon: 'notification',
  },
  {
    id: 71,
    bpid: 7,
    mpid: 7,
    name: '广播',
    icon: 'edit',
    router: '/broadcast/list',
  },
  {
    id: 72,
    bpid: 7,
    mpid: 7,
    name: '广播评论',
    icon: 'message',
    router: '/broadcast/commentlist',
  },
]
